package main

import "fmt"

const transferTemplate = `// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package {{.Package}}

import (
{{- range .Imports }}
	{{.}}
{{- end }}
)

type {{.StructName}}Transfer struct{ {{.StructName}} }

func (t *{{.StructName}}Transfer) Base() {{.StructName}} { return t.{{.StructName}} }
{{range .Fields}}
func (t *{{$.StructName}}Transfer) {{.Getter}}() {{.Type}} { return t.{{$.StructName}}.{{.Name}} }
func (t *{{$.StructName}}Transfer) {{.Setter}}(value {{.Type}}) { t.{{$.StructName}}.{{.Name}} = value }
{{end}}
`

type StructInfo struct {
	Package    string
	StructName string
	Fields     []Field
	Imports    []Import
}

type Field struct {
	Name   string
	Type   string
	Getter string
	Setter string
}

type Import struct {
	Alias string
	Path  string
}

func (i *Import) String() string {
	if i.Alias == "" {
		return fmt.Sprintf(`"%s"`, i.Path)
	}

	return fmt.Sprintf(`%s "%s"`, i.Alias, i.Path)
}
