// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package example

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityDTO struct {
	ID   int
	Name string
}

func (t *EntityDTO) Init(entity Entity) {
	t.ID = entity.ID
	t.Name = entity.name
}

func (t EntityDTO) Base() Entity {
	return Entity{
		ID:   t.ID,
		name: t.Name,
	}
}
