// Code generated by github.com/utherbit/transfer; DO NOT EDIT.

package example

//go:generate go run github.com/utherbit/transfer --type Entity
type EntityDTO struct {
	ID   int
	Name string
}

func (t *EntityDTO) Init(entity Entity) {
	t.ID = entity.ID
	t.Name = entity.name
}

func (t EntityDTO) Base() Entity {
	return Entity{
		ID:   t.ID,
		name: t.Name,
	}
}
