// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package complexTypes

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityTransfer struct {
	MapField        map[string]any
	SliceField      []any
	ArrayField      [1]any
	StructTypeField structType
}

func (t *EntityTransfer) Init(entity Entity) {
	t.MapField = entity.mapField
	t.SliceField = entity.sliceField
	t.ArrayField = entity.arrayField
	t.StructTypeField = entity.structTypeField
}

func (t EntityTransfer) Base() Entity {
	return Entity{
		mapField:        t.MapField,
		sliceField:      t.SliceField,
		arrayField:      t.ArrayField,
		structTypeField: t.StructTypeField,
	}
}
