// Code generated by github.com/utherbit/transfer; DO NOT EDIT.

package multipleNames

//go:generate go run github.com/utherbit/transfer --type Entity
type EntityDTO struct {
	A int
	B int
	C int
}

func (t *EntityDTO) Init(entity Entity) {
	t.A = entity.A
	t.B = entity.B
	t.C = entity.C
}

func (t EntityDTO) Base() Entity {
	return Entity{
		A: t.A,
		B: t.B,
		C: t.C,
	}
}
