// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package multipleNames

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityDTO struct {
	A int
	B int
	C int
}

func (t *EntityDTO) Init(entity Entity) {
	t.A = entity.A
	t.B = entity.B
	t.C = entity.C
}

func (t EntityDTO) Base() Entity {
	return Entity{
		A: t.A,
		B: t.B,
		C: t.C,
	}
}
