// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package ignoreUnderscore

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityTransfer struct {
	_ignorableField int
}

func (t *EntityTransfer) Init(entity Entity) {
	t._ignorableField = entity._ignorableField
}

func (t EntityTransfer) Base() Entity {
	return Entity{
		_ignorableField: t._ignorableField,
	}
}
