// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package case1

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityTransfer struct{ Entity }

func (t *EntityTransfer) Base() Entity { return t.Entity }

func (t *EntityTransfer) Name() string         { return t.Entity.name }
func (t *EntityTransfer) SetName(value string) { t.Entity.name = value }
