// Code generated by github.com/utherbit/transfer; DO NOT EDIT.

package embeddedStruct

import (
	"github.com/utherbit/transfer/internal/testdata/embeddedStruct/pac"
)

//go:generate go run github.com/utherbit/transfer --type Entity
type EntityDTO struct {
	BaseStruct  BaseStruct
	BaseStruct2 *BaseStruct2
	Struct      pac.Struct
	GType       GType[BaseStruct]
}

func (t *EntityDTO) Init(entity Entity) {
	t.BaseStruct = entity.BaseStruct
	t.BaseStruct2 = entity.BaseStruct2
	t.Struct = entity.Struct
	t.GType = entity.GType
}

func (t EntityDTO) Base() Entity {
	return Entity{
		BaseStruct:  t.BaseStruct,
		BaseStruct2: t.BaseStruct2,
		Struct:      t.Struct,
		GType:       t.GType,
	}
}
