// Code generated by klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer; DO NOT EDIT.

package withImports

import (
	"io"
	aliasImport "os"

	"github.com/stretchr/testify/mock"
	"klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer/internal/testdata/withImports/pac"
)

//go:generate go run klad.rupu.ru/rupuru/eda/backend/cmd/gen/transfer --type Entity
type EntityDTO struct {
	ExternalImport *mock.Mock
	InternalImport pac.LocalType
	StdLibImport   io.Reader
	AliasImport    aliasImport.DirEntry
}

func (t *EntityDTO) Init(entity Entity) {
	t.ExternalImport = entity.externalImport
	t.InternalImport = entity.internalImport
	t.StdLibImport = entity.stdLibImport
	t.AliasImport = entity.aliasImport
}

func (t EntityDTO) Base() Entity {
	return Entity{
		externalImport: t.ExternalImport,
		internalImport: t.InternalImport,
		stdLibImport:   t.StdLibImport,
		aliasImport:    t.AliasImport,
	}
}
